version: '3.8'
services:

  app:
    build: ./
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    working_dir: /
    image: consejo_app
    volumes:
      - ./:/var/www/html
    #      - ./docker-files/backend/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: consejo
      MYSQL_ROOT_PASSWORD: consejo
      MYSQL_PASSWORD: consejo
      MYSQL_USER: consejo
    volumes:
      # - ./backend/docker-files/db/my.cnf:/etc/mysql/my.cnf
      - ./database_local:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_USER: consejo
      PMA_PASSWORD: consejo
    ports:
      - 8080:80
    networks:
      - app-network
    links:
      - db:db

networks:
  app-network:
