version: '3.8'
services:

  app:
    build: ./
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    working_dir: /
    image: placasur_app
    volumes:
      # - .:/var/www/html
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    command: bash -c "php /var/www/html/artisan migrate:fresh --seed && php-fpm"
    # command: bash -c "php /var/www/html/artisan migrate && php-fpm"
    # ... otras configuraciones ...
    # restart: always

  db:
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: placasur
      MYSQL_ROOT_PASSWORD: placasur
      MYSQL_PASSWORD: placasur
      MYSQL_USER: placasur
    volumes:
      - ./database_local:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_USER: placasur
      PMA_PASSWORD: placasur
    ports:
      - 8080:80
    networks:
      - app-network
    links:
      - db:db

networks:
  app-network:
