services:

  app:
    build: ./
    working_dir: /var/www/html
    image: placasur_app
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: placasur
      DB_USERNAME: placasur
      DB_PASSWORD: placasur
      VIRTUAL_HOST: placasur.localhost
      VIRTUAL_PORT: 80
    depends_on:
      - db
    networks:
      - app-network
      - shared-web
    # command: bash -c "php /var/www/html/artisan migrate:fresh --seed && php-fpm"

  db:
    image: mariadb:10.8
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: placasur
      MYSQL_ROOT_PASSWORD: placasur
      MYSQL_PASSWORD: placasur
      MYSQL_USER: placasur
    volumes:
      - ./database_local:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_USER: placasur
      PMA_PASSWORD: placasur
      VIRTUAL_HOST: pma.placasur.localhost
    networks:
      - app-network
      - shared-web
    depends_on:
      - db

networks:
  app-network:
  shared-web:
    external: true
